### ISSUE TITLE
Jwt access 토큰 생성 시 클레임 아이디 설정 (이메일 vs Id)

### ISSUE THREAD

**Issue by jhcheon1000** [YoungChaYoungCha/tastynote#18]
``` 
//in JwtUtils.java
public String generateAcceessToken(String userPk) {
    Claims claims = Jwts.claims().setId(userPk);
    ...
    ...
}
```
이메일은 개인 정보이기 때문에 민감하게 다루어야 할텐데 클레임 id를 이메일로 설정해도 문제가 없는지 확인 필요.

**Comment by jhcheon1000** [comment]
찾아봤을 때 claims의 setId는 jti를 설정하는 것으로 확인됨. (jti는 JWT 토큰 식별자)

준희사마한테 물어봤을 때 email로 설정해도 크게 상관없을 거 같다고함. 신경쓰이면 id로 해도 상관없다고 함.

**Comment by hoonkii** [comment]
ㅇㅎㅇㅎ 그렇군 got it

**Comment by hoonkii** [comment]
ID로 하는것으로 결정
